 {
                  "categoryId": "10", 
                  "languageName": "English", 
                  "contentRating": "7", 
                  "additionalLicense": null, 
                  "showName": "jsconf", 
                  "licenseTitle": "Creative Commons Attribution-NonCommercial-ShareAlike 3.0", 
                  "relativeUrl": "/jsconf/nodeconf-2011-ryan-dahl-5420464", 
                  "item_id": 5403235, 
                  "hiddenPassword": null, 
                  "media": {
                        "width": "1280", 
                        "url": "http://blip.tv/file/get/Voodootikigod-NodeConf2011RyanDahl686.mp4", 
                        "duration": "1758", 
                        "mimeType": "video/vnd.objectvideo", 
                        "height": "720"
                  }, 
                  "url": "http://blip.tv/jsconf/nodeconf-2011-ryan-dahl-5420464", 
                  "additionalMedia": [], 
                  "postsGuid": "C0C9042C-B931-11E0-9C9E-AD4917E9B3F2", 
                  "mediaUrl": "http://blip.tv/file/get/Voodootikigod-NodeConf2011RyanDahl686.mp4", 
                  "licenseUrl": "http://creativecommons.org/licenses/by-nc-sa/3.0/", 
                  "revenue": "0.00", 
                  "description": "NodeConf 2011 May 5, 2011 Ryan Dahl", 
                  "datestamp": "07-28-11 11:53am", 
                  "login": "voodootikigod", 
                  "blogUrl": "http://jsconf.us/2010", 
                  "itemId": 5403235, 
                  "lockAdvertising": "0", 
                  "licenseId": "13", 
                  "title": "NodeConf 2011 - Ryan Dahl", 
                  "nsfw": "0", 
                  "adminDescription": "NodeConf 2011 May 5, 2011 Ryan Dahl", 
                  "datestampText": "Jul 28, 2011", 
                  "thumbnail120Url": "http://a.images.blip.tv/", 
                  "distributions": [ ], 
                  "conversions": [], 
                  "embedUrl": "http://blip.tv/play/g_MngsrsFAI", 
                  "playlists": null, 
                  "views": "1862", 
                  "thumbnailFilename": "Voodootikigod-NodeConf2011RyanDahl686-162.jpg", 
                  "embedLookup": "g_MngsrsFAI", 
                  "adsEnabled": null, 
                  "nextHiddenDate": null, 
                  "languageCode": "en", 
                  "numMidrolls": null, 
                  "adminTitle": "NodeConf 2011 - Ryan Dahl", 
                  "postsId": 5420464, 
                  "thumbnailUrl": "http://a.images.blip.tv/Voodootikigod-NodeConf2011RyanDahl686-162.jpg", 
                  "midrollStart": null, 
                  "userId": "407879", 
                  "adOptOut": "1", 
                  "midrollDuration": null, 
                  "display_name": "jsconf", 
                  "tags": [], 
                  "categoryName": "Conferences and Other Events", 
                  "itemType": "file", 
                  "hidden": "0", 
                  "youtube_description": null
            }, 
